# -------------------------- Parameters for training the model --------------------------#

# Wether to use 32 or 64 model
model_type: 64

# Network configuration
kernel_size: 3
stride: 1
padding: 1

# Training configuration
epochs: 50 # Number of epochs to train the model
test_train_split: 0.8 # Percentage of data to use for training
learning_rate: 0.001 # Learning rate for the optimizer
training_data_size: 1000 # Number of examples to use for training

# Dataset directory used for training model
dataset_path: "Dataset_64"

# Model save name
model_name: "CNN_64_k3_1k"

# -------------------------- Parameters for loading the model --------------------------#

# Model loader settings
model_path: "Models/CNN_64_k3_1k.pt"
shape_data_path: "Dataset_64/shape"

# Number of examples to load to save as images
examples: 10
example_path: "Examples"  

